name: CI
# Định nghĩa các sự kiện gây ra sẽ kích hoạt quy trình
on:
  push:
    branches:
      - develop
      - main
      - release
  pull_request:
    type: [opened, reopened, synchronize, labeled, unlabeled]
    branches:
      - develop

jobs:
  # Công việc để kiểm tra phiên bản
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      # sao chép
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
        # Cài đặt các phụ thuộc (dependencies).
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  codacy-security-scan:
    needs: check-bats-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Codacy GitHub Action
        uses: codacy/coverage-action@v1
        with:
          # chạy quét và báo cáo kết quả.
          # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/coverage-final.json
